# Generated by Django 4.0 on 2023-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to=''),
        ),
    ]
