# Generated by Django 4.0 on 2023-04-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
