# Generated by Django 4.0 on 2023-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookauthor_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
